services:
  trade-imports-defra-id-stub:
    ports:
      - '${TRADE_IMPORTS_DEFRA_ID_STUB_PORT:-3007}:${TRADE_IMPORTS_DEFRA_ID_STUB_PORT:-3007}'
    networks:
      - trade-imports-defra-id-stub
    volumes:
      - ./example.data.json:/data/example.data.json

  localstack:
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - ./scripts/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
      - localstack-data:/var/lib/localstack
    networks:
      - trade-imports-defra-id-stub

  redis:
    networks:
      - trade-imports-defra-id-stub

networks:
  trade-imports-defra-id-stub:
    driver: bridge
    name: trade-imports-defra-id-stub

volumes:
  localstack-data:
